UTF8PROC_S7_VERSION = "2.8.0"
UTF8PROC_VERSION = "2.8.0"
LIBS7_VERSION = "0.1.0"

GOPT_VERSION = "10.0.0"
LIBLOG_CC_VERSION = "1.0.0"
UNITY_VERSION = "2.5.2"
UTHASH_VERSION = "2.3.0"

BASE_SRCS = []
BASE_DEPS = [
    "@libs7//src:s7",
]
BASE_INCLUDE_PATHS = [
    "-Iexternal/libs7~{}/src".format(LIBS7_VERSION),
]
BASE_COPTS = []
BASE_DEFINES = []
BASE_LINKOPTS = []
TIMEOUT = "short"
